<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://dev.sourceafrica.net:8080
  cloud_crowd_console:  http://dev.sourceafrica.net:8080
  server_root:          dev.dcloud.org
  asset_root:           dev.dcloud.org
  workspace_asset_root: assets.dcloud.org
  large_file_storage:   /mnt/large_files
  aws_region:           eu-west-1
  aws_zone:             eu-west-1c
  preconfigured_ami_id: <%= secrets['ami'] %>
  google_analytics_id:  <%= secrets['google_analytics_id'] %>
  platform_name:        <%= secrets['platform_name'] %>
  platform_domain:      <%= secrets['platform_domain'] %>
  twitter_username:     '<%= secrets['twitter_username'] %>'

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server:   <%= secrets['db_host'] %>:8080
  cloud_crowd_console:  staging.sourceafrica.net:8080
  server_root:          staging.sourceafrica.net
  asset_root:           s3-eu-west-1.amazonaws.com/s3.staging.sourceafrica.net
  workspace_asset_root: s3-eu-west-1.amazonaws.com/s3.staging.sourceafrica.net

production:
  <<: *defaults
  cloud_crowd_server:   <%= secrets['db_host'] %>:8080
  cloud_crowd_console:  dc.sourceafrica.net:8080
  server_root:          dc.sourceafrica.net
  asset_root:           s3-eu-west-1.amazonaws.com/s3.sourceafrica.net
  workspace_asset_root: s3-eu-west-1.amazonaws.com/s3.sourceafrica.net

test:
  <<: *defaults
