# Sensitive API keys and other secret strings.

defaults : &defaults
  secret_key_base: # Generate this by running: rake secret
  platform_name:  # What you call your installation of DocumentCloud
  platform_domain: # domain (minus subdomain) of your installation
  aws_account_id: 
  aws_access_key: 
  aws_secret_key: 
  cloudfront_access_key: 
  cloudfront_secret_key: 
  cloudfront_distribution_id: 
  calais_license: 
  calais_api_limit: 
  pixel_ping: # The secret hashed key for Pixel Ping (keep in sync with secrets/pixel_ping/:env.json)
  guest_username: # The username used for logging into basic auth in staging
  guest_password: # The password used for logging into basic auth in staging
  username: # The database username
  db_password: # The database password
  smtp_password: 
  smtp_user: 
  smtp_host: 
  smtp_domain: 
  slack_webhook: 
  ami: 
  aws_ssh_key_name: 
  aws_security_group: 
  twitter_username: # If your platform has one, its Twitter username (including `@`)
  google_analytics:
  google_drive:
    key: 
    secret: 
  google_recaptcha:
    key: 
    secret: 
  stripe:
    secret: 
    publish: 

development :
  <<: *defaults
  email_upload_secret: 
  cloud_crowd_secret: 
  elasticsearch_hosts:
    - localhost

staging :
  <<: *defaults
  email_upload_secret: 
  cloud_crowd_secret: 
  bucket: # the s3 bucket to store both documents and the viewer in
  db_host: # the hostname for your database server
  solr_host: # the hostname for your solr server
  job_end_point: # the hostname for your cloud-crowd server
  central_server: # the fully qualified (private) url for the cloud-crowd server (e.g. http://ip-44-555-66-777.ec2.internal:8080)
  smtp_user: 
  smtp_password: 
  smtp_host: 

test :
  <<: *defaults

## EC2 private IP addresses should only be used here
## Communicating via public ip address incurs bandwidth charges
## at the Regional Data Transfer rates
production :
  <<: *defaults
  bucket: 
  db_host: 
  solr_host: 
  job_end_point: 
  central_server: 
  smtp_user: 
  smtp_password: 
  smtp_host: 
  email_upload_secret: 
  cloud_crowd_secret: 
  google:
    analytics:
  stripe:
    secret: 
    publish: 

elastic :
  <<: *defaults
  bucket: 
  db_host: 
  central_server: 
  job_end_point: 
  smtp_user: 
  smtp_password: 
  smtp_host: 
  elasticsearch_hosts:
    - 
    - 
